server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: bfhl

# Configurable profile details for BFHL API
bfhl:
  user:
    full-name: akshara_shukla
    dob: "23072003"
    email: aksharashukla2307171@acropolis.in
    roll-number: 0827CS231025

# Enable clean logging formatting
logging:
  level:
    root: INFO
    com.bajaj.bfhl: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
