# Server Port Configuration (Railway binds this dynamically using PORT env variable)
server.port=${PORT:8080}

# Application Name
spring.application.name=bfhl

# Custom properties to define the challenge participant profile details
bfhl.user.full-name=akshara_shukla
bfhl.user.dob=23072003
bfhl.user.email=aksharashukla2307171@acropolis.in
bfhl.user.roll-number=0827CS231025

# Show detailed validation and binding messages on startup
server.error.include-message=always
logging.level.root=INFO
logging.level.com.bajaj.bfhl=DEBUG
